apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: new
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: new
    app.kubernetes.io/part-of: new
  name: new
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: new
status:
  loadBalancer: {}
