apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: new
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-csears-tenant/new/new@sha256:914151ff231182214a4291a8034306e574b149ec1f8afdba612ae2f9ecd57051
        name: my-java-springboot
        resources: {}
status: {}
